//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSaveSwapper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameSaveSwapper.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another profile that already contains that name..
        /// </summary>
        public static string AddProfile_ExistingName {
            get {
                return ResourceManager.GetString("AddProfile_ExistingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this profile?.
        /// </summary>
        public static string DeleteProfileConfirm_Content {
            get {
                return ResourceManager.GetString("DeleteProfileConfirm_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        public static string DeleteProfileConfirm_Title {
            get {
                return ResourceManager.GetString("DeleteProfileConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are files in the profile save location, do you wish to delete them? .
        /// </summary>
        public static string DeleteProfileExisting_Content {
            get {
                return ResourceManager.GetString("DeleteProfileExisting_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Files in Save Location.
        /// </summary>
        public static string DeleteProfileExisting_Title {
            get {
                return ResourceManager.GetString("DeleteProfileExisting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is save files for this game that do not belong to a certain profile. You can move these by using the &apos;Move Existing Saves Here&apos; on a profile. 
        ///Do you want to continue &amp; delete this save?.
        /// </summary>
        public static string EmptySaves_ExistingFiles_Content {
            get {
                return ResourceManager.GetString("EmptySaves_ExistingFiles_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use &apos;Move Existing Saves Here&apos; to set where the game&apos;s current save files should go to..
        /// </summary>
        public static string EmptySaves_ExistingFiles_TIP {
            get {
                return ResourceManager.GetString("EmptySaves_ExistingFiles_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game&apos;s save directory has a save for a profile that does not exist. Do you wish to continue &amp; delete any save data? You can move the files using &apos;Move Existing Saves Here&apos; on a profile to keep the data..
        /// </summary>
        public static string EmptySaves_UnknownProfile_Content {
            get {
                return ResourceManager.GetString("EmptySaves_UnknownProfile_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Swapper Profile.
        /// </summary>
        public static string EmptySaves_UnknownProfile_Title {
            get {
                return ResourceManager.GetString("EmptySaves_UnknownProfile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to empty the game save directory..
        /// </summary>
        public static string EmptySavesFailed_Content {
            get {
                return ResourceManager.GetString("EmptySavesFailed_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Game Saves Failed.
        /// </summary>
        public static string EmptySavesFailed_Title {
            get {
                return ResourceManager.GetString("EmptySavesFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your first time using GameSaveSwapper, do you want to add a new game?.
        /// </summary>
        public static string FirstTimeSetup_Content {
            get {
                return ResourceManager.GetString("FirstTimeSetup_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Time Setup.
        /// </summary>
        public static string FirstTimeSetup_Title {
            get {
                return ResourceManager.GetString("FirstTimeSetup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile folder already contains profile data, do you wish to continue? (This will overwrite existing files!).
        /// </summary>
        public static string MoveExisting_ExistingData_Content {
            get {
                return ResourceManager.GetString("MoveExisting_ExistingData_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Files in Destination.
        /// </summary>
        public static string MoveExisting_ExistingData_Title {
            get {
                return ResourceManager.GetString("MoveExisting_ExistingData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exe has been specified for this game..
        /// </summary>
        public static string PlayProfile_MissingExe_Content {
            get {
                return ResourceManager.GetString("PlayProfile_MissingExe_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing EXE Path.
        /// </summary>
        public static string PlayProfile_MissingExe_Title {
            get {
                return ResourceManager.GetString("PlayProfile_MissingExe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Already Exists.
        /// </summary>
        public static string ProfileAdd_ExistingNameTitle {
            get {
                return ResourceManager.GetString("ProfileAdd_ExistingNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a game for this profile.
        /// </summary>
        public static string ProfileAdd_ProvideGame_Content {
            get {
                return ResourceManager.GetString("ProfileAdd_ProvideGame_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Profile Game.
        /// </summary>
        public static string ProfileAdd_ProvideGame_Title {
            get {
                return ResourceManager.GetString("ProfileAdd_ProvideGame_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a profile name.
        /// </summary>
        public static string ProfileAdd_ProvideName_Content {
            get {
                return ResourceManager.GetString("ProfileAdd_ProvideName_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Profile Name.
        /// </summary>
        public static string ProfileAdd_ProvideName_Title {
            get {
                return ResourceManager.GetString("ProfileAdd_ProvideName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a profile to rename.
        /// </summary>
        public static string Rename_NoProfileFound_Content {
            get {
                return ResourceManager.GetString("Rename_NoProfileFound_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Profile.
        /// </summary>
        public static string Rename_NoProfileFound_Title {
            get {
                return ResourceManager.GetString("Rename_NoProfileFound_Title", resourceCulture);
            }
        }
    }
}
